// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    createBlazeTemplate: function(options) {
      var myString;
      console.log("generating Blaze Template...");
      myString = "   <template name=\"" + options['name'] + "\">\n{{" + options['data'] + "}}</p>\n   </template>";
      return myString;
    },
    createStructure: function(structureId, name) {
      return console.log("created " + structureId + " " + name);
    }
  };

}).call(this);
