// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    createBlazeTemplate: function(options) {
      return console.log("generated Blaze Template");
    },
    createStructure: function(structureId, name) {
      return console.log("created " + structureId + " " + name);
    }
  };

}).call(this);
