// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    createBlazeTemplate: function(options) {
      var myString;
      console.log("generating Blaze Template...");
      myString = "<template name=\"" + options['name'] + "\">\n  <button>Click Me</button>\n  <p>Sam pressed the button {{" + options['data'] + "}} times.</p>\n</template>";
      return myString;
    },
    createStructure: function(structureId, name) {
      return console.log("created " + structureId + " " + name);
    }
  };

}).call(this);
